name: Deploy

on:
  push:
    tags:
      # Regex for a version number such as 0.2.1
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: $\{\{ matrix.os \}\}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Rust
        # Or @nightly if you want
        uses: dtolnay/rust-toolchain@stable
        # Arguments to pass in
        with:
          # Make Rust compile to our target (defined in the matrix)
          targets: $\{\{ matrix.target \}\}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --bin=hollow-cli --target $\{\{ matrix.target \}\}

      - name: Build archive
        shell: bash
        run: |
          # Replace with the name of your binary
          binary_name="hollow"

          dirname="$binary_name-$\{\{ env.VERSION \}\}-$\{\{ matrix.target \}\}"
          mkdir "$dirname"
          if [ "$\{\{ matrix.os \}\}" = "windows-latest" ]; then
            mv "target/$\{\{ matrix.target \}\}/release/$binary_name.exe" "$dirname"
          else
            mv "target/$\{\{ matrix.target \}\}/release/$binary_name" "$dirname"
          fi

          if [ "$\{\{ matrix.os \}\}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload the binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            $\{\{ env.ASSET \}\}
